### ISSUE TITLE
request is bad

### ISSUE THREAD

**Issue by vankasteelj** [ChrisAlderson/fanart.tv-api#1]
and you should feel bad 😄 

I might have made https://github.com/vankasteelj/fanart.tv just to avoid using request

**Comment by ChrisAlderson** [comment]
So why should I use `got` instead of `request`?

**Comment by vankasteelj** [comment]
because request :
- uses callbacks
- weights multiple megabytes

**Comment by ChrisAlderson** [comment]
Callbacks I don't mind because I always make a helper method which wraps the callback in a `Promise` object as shown [here](https://github.com/ChrisAlderson/fanart.tv-api/blob/master/fanart.tv-api.js#L21).

I can see why someone would want a small module, like this one, use a small and compact HTTP request client.

Overall these two points don't make me feel bad 😄

**Comment by vankasteelj** [comment]
Ok then, it was just to point out request wasn't good enough imo, mainly because of the weight. Note that there's a minor issue (maybe?) with the wording of your functions, there's "latest" and "lastest", probably a typo. :)

**Comment by ChrisAlderson** [comment]
oh yea I created this a bit hasty, so thanks for pointing out the typo.
